version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 199811
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: parking-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: parking_db
      DB_USER: postgres
      DB_PASSWORD: 199811
    volumes:
      - .:/usr/src/app
    command: sh entrypoint.sh

volumes:
  pgdata:
