version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 199811
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
